enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
build-mode = "both"
excluded-patches = ""
arch = "arm64-v8a"                                         # 'arm64-v8a', 'arm-v7a', 'all', 'both'. 'both' downloads both arm64-v8a and arm-v7a. default: all

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
build-mode = "apk"
#module-prop-name = "reddit-vanced"                       # magisk module prop name.

[Boost]
apkmirror-dlurl = "https://www.apkmirror.com/apk/ruben-mayayo/boost-for-reddit/"
build-mode = "apk"
patcher-args = "-Oclient-id=3f1BRnssrLen465fGtsWYA "
#module-prop-name = "boost-vanced"                       # magisk module prop name.
version = "latest"
arch = "arm64-v8a"                                         # 'arm64-v8a', 'arm-v7a', 'all', 'both'. 'both' downloads both arm64-v8a and arm-v7a. default: all

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
included-patches = "'Enable slide to seek'"
excluded-patches = "'Return YouTube Dislike' 'Shorts autoplay'"
arch = "arm64-v8a"                                         # 'arm64-v8a', 'arm-v7a', 'all', 'both'. 'both' downloads both arm64-v8a and arm-v7a. default: all

[ml.docilealligator.infinityforreddit]
app-name = "Infinity"
apkmirror-dlurl = "https://www.apkmirror.com/apk/docile-alligator/infinity-for-reddit/"
build-mode = "apk"
patcher-args = "-Oclient-id=rTVdw2HOxK7Z2_Nlo4BYFw "
#module-prop-name = "infinity-vanced"                       # magisk module prop name.
version = "latest"
